# Generated by Django 4.1 on 2022-08-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IPL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=250)),
                ("date", models.DateTimeField(default="")),
                ("player_of_match", models.CharField(max_length=250)),
                ("venue", models.CharField(max_length=250)),
                ("neutral_venue", models.CharField(max_length=250)),
                ("team1", models.CharField(max_length=250)),
                ("team2", models.CharField(max_length=250)),
                ("toss_winner", models.CharField(max_length=250)),
                ("toss_decision", models.CharField(max_length=250)),
                ("winner", models.CharField(max_length=250)),
                ("result", models.CharField(max_length=250)),
                ("result_margin", models.CharField(max_length=250)),
                ("eliminator", models.CharField(max_length=250)),
                ("method", models.CharField(max_length=250)),
                ("umpire1", models.CharField(max_length=250)),
                ("umpire2", models.CharField(max_length=250)),
            ],
        ),
    ]
